#!/usr/bin/env bash
# =============================================================================
# setup_server.sh — Dev-mode deployment for ChatDF on Ubuntu VPS
# Domain: datachatdata.com (Cloudflare DNS)
#
# Architecture:
#   Nginx (443 SSL) ──┬── /auth, /conversations, /usage, /ws → Uvicorn :8000
#                      └── everything else → Vite dev server :5173
#
# Both servers run with hot-reload — edit files and changes appear instantly.
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DOMAIN="datachatdata.com"
APP_DIR="/home/ubuntu/chatDF"
BACKEND_DIR="$APP_DIR/implementation/backend"
FRONTEND_DIR="$APP_DIR/implementation/frontend"
VENV_DIR="$BACKEND_DIR/.venv"
SSL_DIR="/etc/ssl/chatdf"
NGINX_CONF="/etc/nginx/sites-available/chatdf"

UV_BIN="/home/ubuntu/.local/bin/uv"
BUN_BIN="/home/ubuntu/.bun/bin/bun"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }
step() { echo -e "\n${CYAN}==== $* ====${NC}"; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (use: sudo bash setup_server.sh)"
    exit 1
fi

if [[ ! -d "$APP_DIR" ]]; then
    err "Application directory $APP_DIR not found"
    exit 1
fi

# ---------------------------------------------------------------------------
# Step 1: System dependencies
# ---------------------------------------------------------------------------
step "1/8  Installing system dependencies"

apt-get update -qq
apt-get install -y -qq \
    nginx \
    python3 \
    python3-venv \
    python3-dev \
    build-essential \
    curl \
    unzip \
    sqlite3 \
    ufw > /dev/null

log "System packages installed"

# ---------------------------------------------------------------------------
# Step 2: Install uv and bun (as ubuntu user)
# ---------------------------------------------------------------------------
step "2/8  Installing uv and bun"

if [[ ! -x "$UV_BIN" ]]; then
    su -l ubuntu -c 'curl -LsSf https://astral.sh/uv/install.sh | sh'
    log "uv installed → $UV_BIN"
else
    log "uv already installed ($("$UV_BIN" --version))"
fi

if [[ ! -x "$BUN_BIN" ]]; then
    su -l ubuntu -c 'curl -fsSL https://bun.sh/install | bash'
    log "bun installed → $BUN_BIN"
else
    log "bun already installed ($("$BUN_BIN" --version))"
fi

# ---------------------------------------------------------------------------
# Step 3: Backend setup (venv + dependencies)
# ---------------------------------------------------------------------------
step "3/8  Setting up backend"

cd "$BACKEND_DIR"

if [[ ! -d "$VENV_DIR" ]]; then
    su -l ubuntu -c "cd $BACKEND_DIR && $UV_BIN venv .venv"
    log "Virtual environment created"
fi

su -l ubuntu -c "cd $BACKEND_DIR && $UV_BIN pip install -e '.' --python .venv/bin/python"
log "Backend dependencies installed"

# ---------------------------------------------------------------------------
# Step 4: Frontend dependencies (no build — Vite dev server serves directly)
# ---------------------------------------------------------------------------
step "4/8  Installing frontend dependencies"

su -l ubuntu -c "cd $FRONTEND_DIR && $BUN_BIN install --ignore-scripts"
log "Frontend dependencies installed"

# ---------------------------------------------------------------------------
# Step 5: Environment file
# ---------------------------------------------------------------------------
step "5/8  Configuring environment"

ENV_FILE="$BACKEND_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env file already exists at $ENV_FILE"
    read -rp "Overwrite it? (y/N): " overwrite
    if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
        log "Keeping existing .env"
    else
        rm "$ENV_FILE"
    fi
fi

if [[ ! -f "$ENV_FILE" ]]; then
    echo ""
    echo "We need your API credentials. You can leave blank and fill in later."
    echo ""

    read -rp "GEMINI_API_KEY: " GEMINI_KEY
    read -rp "GOOGLE_CLIENT_ID: " GOOGLE_CID
    read -rp "GOOGLE_CLIENT_SECRET: " GOOGLE_CSECRET

    cat > "$ENV_FILE" << EOF
# ChatDF Environment
# Generated by setup_server.sh on $(date -Iseconds)

# Required — API keys
GEMINI_API_KEY=${GEMINI_KEY}
GOOGLE_CLIENT_ID=${GOOGLE_CID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CSECRET}

# Settings
DATABASE_URL=sqlite:///${BACKEND_DIR}/chatdf.db
CORS_ORIGINS=https://${DOMAIN}
TOKEN_LIMIT=5000000
WORKER_MEMORY_LIMIT=512
WORKER_POOL_SIZE=4
SESSION_DURATION_DAYS=7
SECURE_COOKIES=true
EOF

    chown ubuntu:ubuntu "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log ".env created (permissions: 600)"
fi

# ---------------------------------------------------------------------------
# Step 6: SSL certificate (Cloudflare Origin Certificate)
# ---------------------------------------------------------------------------
step "6/8  Setting up SSL"

mkdir -p "$SSL_DIR"

if [[ -f "$SSL_DIR/cert.pem" && -f "$SSL_DIR/key.pem" ]]; then
    log "SSL certificates already exist in $SSL_DIR"
else
    echo ""
    echo "Cloudflare Origin Certificate setup:"
    echo ""
    echo "  1. Go to: Cloudflare Dashboard → ${DOMAIN} → SSL/TLS → Origin Server"
    echo "  2. Click 'Create Certificate'"
    echo "  3. Keep defaults (RSA 2048, 15 years, covers ${DOMAIN} and *.${DOMAIN})"
    echo "  4. Copy the Origin Certificate and Private Key"
    echo ""
    echo "Choose an option:"
    echo "  1) Paste certificate and key now"
    echo "  2) Generate a self-signed cert for now (replace later)"
    echo ""
    read -rp "Option (1/2): " ssl_option

    if [[ "$ssl_option" == "1" ]]; then
        echo ""
        echo "Paste your Origin Certificate PEM, then press Ctrl+D:"
        cert_content=$(cat)
        echo "$cert_content" > "$SSL_DIR/cert.pem"

        echo ""
        echo "Paste your Private Key PEM, then press Ctrl+D:"
        key_content=$(cat)
        echo "$key_content" > "$SSL_DIR/key.pem"

        log "Cloudflare Origin Certificate installed"
    else
        openssl req -x509 -nodes -days 365 \
            -newkey rsa:2048 \
            -keyout "$SSL_DIR/key.pem" \
            -out "$SSL_DIR/cert.pem" \
            -subj "/CN=${DOMAIN}" \
            -addext "subjectAltName=DNS:${DOMAIN},DNS:www.${DOMAIN}" \
            2>/dev/null

        warn "Self-signed certificate generated (replace with Cloudflare Origin Cert later)"
    fi

    chmod 600 "$SSL_DIR/key.pem"
    chmod 644 "$SSL_DIR/cert.pem"
fi

# ---------------------------------------------------------------------------
# Step 7: Nginx + systemd services
# ---------------------------------------------------------------------------
step "7/8  Configuring Nginx and services"

# --- Nginx config: proxy to Vite dev server + Uvicorn ---
cat > "$NGINX_CONF" << 'NGINX_EOF'
# ChatDF — datachatdata.com (dev mode)
# Nginx routes: API → Uvicorn :8000, everything else → Vite :5173

# Redirect HTTP → HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name datachatdata.com www.datachatdata.com;
    return 301 https://datachatdata.com$request_uri;
}

# Redirect www → apex
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.datachatdata.com;

    ssl_certificate     /etc/ssl/chatdf/cert.pem;
    ssl_certificate_key /etc/ssl/chatdf/key.pem;

    return 301 https://datachatdata.com$request_uri;
}

# Main server block
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name datachatdata.com;

    # --- SSL ---
    ssl_certificate     /etc/ssl/chatdf/cert.pem;
    ssl_certificate_key /etc/ssl/chatdf/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # --- Security headers ---
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # --- API routes → Uvicorn (backend :8000) ---
    location /auth/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /conversations {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }

    location /usage {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # --- WebSocket → Uvicorn ---
    location /ws {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # --- Everything else → Vite dev server (frontend :5173) ---
    location / {
        proxy_pass http://127.0.0.1:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Vite HMR WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
NGINX_EOF

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/chatdf
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable nginx
systemctl reload nginx
log "Nginx configured"

# --- Backend service: uvicorn with --reload ---
cat > /etc/systemd/system/chatdf-backend.service << EOF
[Unit]
Description=ChatDF Backend (uvicorn --reload)
After=network.target

[Service]
Type=exec
User=ubuntu
Group=ubuntu
WorkingDirectory=${BACKEND_DIR}
EnvironmentFile=${BACKEND_DIR}/.env
ExecStart=${VENV_DIR}/bin/uvicorn app.main:app \\
    --host 127.0.0.1 \\
    --port 8000 \\
    --reload \\
    --proxy-headers \\
    --forwarded-allow-ips="127.0.0.1"

Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

# --- Frontend service: Vite dev server ---
cat > /etc/systemd/system/chatdf-frontend.service << EOF
[Unit]
Description=ChatDF Frontend (Vite dev server)
After=network.target

[Service]
Type=exec
User=ubuntu
Group=ubuntu
WorkingDirectory=${FRONTEND_DIR}
Environment=PATH=/home/ubuntu/.bun/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=${BUN_BIN} run dev --host 0.0.0.0 --port 5173

Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable chatdf-backend chatdf-frontend
systemctl restart chatdf-backend chatdf-frontend

sleep 3

# Check services
for svc in chatdf-backend chatdf-frontend; do
    if systemctl is-active --quiet "$svc"; then
        log "$svc is running"
    else
        err "$svc failed to start. Check: journalctl -u $svc -n 30"
    fi
done

# ---------------------------------------------------------------------------
# Step 8: Firewall
# ---------------------------------------------------------------------------
step "8/8  Configuring firewall"

ufw --force reset > /dev/null 2>&1
ufw default deny incoming > /dev/null
ufw default allow outgoing > /dev/null
ufw allow 22/tcp > /dev/null    # SSH
ufw allow 80/tcp > /dev/null    # HTTP (redirects to HTTPS)
ufw allow 443/tcp > /dev/null   # HTTPS
ufw --force enable > /dev/null

log "Firewall enabled (SSH + HTTP + HTTPS)"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
VPS_IP=$(curl -s --max-time 5 ifconfig.me || echo '<YOUR_VPS_IP>')

echo ""
echo "============================================================"
echo -e "${GREEN}  ChatDF is running in dev mode!${NC}"
echo "============================================================"
echo ""
echo "  Services:"
echo "    Backend:  systemctl status chatdf-backend   (uvicorn --reload :8000)"
echo "    Frontend: systemctl status chatdf-frontend   (vite dev :5173)"
echo "    Nginx:    systemctl status nginx              (SSL proxy :443)"
echo ""
echo "  Logs:"
echo "    journalctl -u chatdf-backend -f"
echo "    journalctl -u chatdf-frontend -f"
echo ""
echo "  Restart after code changes (auto-reload handles most, but if needed):"
echo "    sudo systemctl restart chatdf-backend chatdf-frontend"
echo ""
echo "  Remaining steps:"
echo ""
echo "  1. CLOUDFLARE DNS"
echo "     → A record: ${DOMAIN} → ${VPS_IP}"
echo "     → Proxy status: Proxied (orange cloud)"
echo ""
echo "  2. CLOUDFLARE SSL/TLS"
echo "     → Encryption mode: Full (Strict)"
echo ""
echo "  3. GOOGLE OAUTH (Google Cloud Console)"
echo "     → Authorized redirect URI:"
echo "       https://${DOMAIN}/auth/google/callback"
echo ""
echo "  4. FILL IN .env (if you skipped credentials)"
echo "     → nano ${BACKEND_DIR}/.env"
echo "     → sudo systemctl restart chatdf-backend"
echo ""
echo "============================================================"
